SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Drop and Recreate Database
DROP DATABASE IF EXISTS `school`;
CREATE DATABASE `school` CHARACTER SET = 'utf8mb4' COLLATE = 'utf8mb4_unicode_ci';
USE `school`;

-- -----------------------------------------------------
-- Table: teachers
-- -----------------------------------------------------
CREATE TABLE `teachers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL COMMENT 'Stores the Bcrypt hash generated by PHP',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_teachers_email` (`email`),
  KEY `idx_teachers_name` (`last_name`, `first_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table: students
-- -----------------------------------------------------
CREATE TABLE `students` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `dob` DATE NOT NULL,
  `enrollment_date` DATE NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_students_email` (`email`),
  KEY `idx_students_name` (`last_name`, `first_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table: classes
-- -----------------------------------------------------
CREATE TABLE `classes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `teacher_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_classes_name` (`name`),
  CONSTRAINT `fk_classes_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `teachers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table: enrollments (Pivot Table)
-- -----------------------------------------------------
CREATE TABLE `enrollments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` BIGINT UNSIGNED NOT NULL,
  `class_id` BIGINT UNSIGNED NOT NULL,
  `enrolled_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_student_class` (`student_id`, `class_id`),
  KEY `idx_enrollments_student` (`student_id`),
  KEY `idx_enrollments_class` (`class_id`),
  CONSTRAINT `fk_enrollments_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_enrollments_class` FOREIGN KEY (`class_id`) REFERENCES `classes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- DUMMY DATA INSERTION
-- -----------------------------------------------------

-- 1. Insert Teachers
-- NOTE: The password for both accounts is 'password'.
-- We insert the pre-calculated Bcrypt hash because MySQL cannot natively generate
-- the specific hash format ($2y$10$...) that Laravel requires for authentication.
INSERT INTO `teachers` (`first_name`, `last_name`, `email`, `password`)
VALUES
  ('Alice', 'Martinez', 'alice@school.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
  ('Brian', 'Lopez',    'brian@school.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi');

-- 2. Insert Classes
INSERT INTO `classes` (`name`, `description`, `teacher_id`)
VALUES
  ('Mathematics 101', 'Introduction to Algebra', 1),
  ('Science 202', 'Basic Chemistry and Physics', 2),
  ('History 303', 'World History', 1);

-- 3. Insert Students
INSERT INTO `students` (`first_name`, `last_name`, `email`, `dob`, `enrollment_date`)
VALUES
  ('Carlos', 'Gomez', 'carlos@student.com', '2010-05-15', '2023-09-01'),
  ('Diana',  'Rivera', 'diana@student.com',  '2011-08-20', '2023-09-01'),
  ('Elena',  'Torres', 'elena@student.com',  '2010-12-10', '2024-01-15');

-- 4. Enroll Students
INSERT INTO `enrollments` (`student_id`, `class_id`)
VALUES
  (1, 1),
  (1, 2),
  (2, 1),
  (3, 3);

SET FOREIGN_KEY_CHECKS = 1;